# Generated by Django 5.1.6 on 2025-07-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100)),
                ('org_reg_number', models.CharField(max_length=50, unique=True)),
                ('org_type', models.CharField(max_length=50)),
                ('org_established_yer', models.PositiveIntegerField()),
                ('org_address', models.TextField()),
                ('org_city', models.CharField(max_length=50)),
                ('org_state', models.CharField(max_length=50)),
                ('org_country', models.CharField(max_length=50)),
                ('org_pincode', models.CharField(max_length=10)),
                ('org_contact_person', models.CharField(max_length=100)),
                ('org_contact_email', models.EmailField(max_length=254)),
                ('org_contact_phone', models.CharField(max_length=15)),
                ('org_registered_doc', models.FileField(upload_to='org_documents/')),
                ('org_agree_to_terms', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('verified', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_fname', models.CharField(max_length=100)),
                ('volunteer_email', models.EmailField(max_length=254, unique=True)),
                ('volunteer_phno', models.CharField(max_length=15, unique=True)),
                ('volunteer_dob', models.DateField()),
                ('volunteer_city', models.CharField(max_length=50)),
                ('volunteer_state', models.CharField(max_length=50)),
                ('volunteer_pincode', models.CharField(max_length=10)),
                ('volunteer_skill', models.CharField(max_length=100)),
                ('volunteer_experience_years', models.PositiveIntegerField()),
                ('volunteer_availability', models.CharField(max_length=100)),
                ('volunteer_consent_public', models.BooleanField(default=True)),
                ('volunteer_agree_to_terms', models.BooleanField(default=False)),
            ],
        ),
    ]
