# Generated by Django 5.1.7 on 2025-10-29 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('about', models.CharField(max_length=500)),
                ('org_type', models.CharField(choices=[('NGO', 'NGO'), ('Research Group', 'Research Group'), ('Education Institute', 'Education Institute'), ('Charity', 'Charity')], max_length=50)),
                ('address', models.TextField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('skills', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('skills_required', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('total_volunteers_needed', models.PositiveIntegerField()),
                ('applied', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.CharField(blank=True, max_length=100, null=True)),
                ('end_time', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='static/campaign_banners/')),
                ('additional_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('postedBy', models.CharField(max_length=200)),
                ('organizationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahyogamApp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='InviteCampaing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('skills_required', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.CharField(blank=True, max_length=100, null=True)),
                ('end_time', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('certificate_approved', models.BooleanField(default=False)),
                ('OrganizationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahyogamApp.organization')),
                ('VolunteerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahyogamApp.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('certificate_approved', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahyogamApp.campaign')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahyogamApp.volunteer')),
            ],
        ),
    ]
