# Generated by Django 5.1.7 on 2025-10-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahyogamApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
