# Generated by Django 5.2.5 on 2025-08-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahyogamApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
