# Generated by Django 5.1.7 on 2025-10-29 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahyogamApp', '0002_alter_organization_about_alter_organization_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='static/certificates/')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sahyogamApp.campaign')),
                ('invite_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sahyogamApp.invitecampaing')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahyogamApp.organization')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahyogamApp.volunteer')),
            ],
        ),
    ]
