# Generated by Django 5.2.5 on 2025-08-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahyogamApp', '0002_organization_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTPVerification',
            new_name='EmailOTP',
        ),
    ]
