# Generated by Django 5.2.5 on 2025-08-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahyogamApp', '0003_rename_otpverification_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
