# Generated by Django 5.2.5 on 2025-08-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahyogamApp', '0004_volunteer_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='volunteer/'),
        ),
    ]
