# Generated by Django 5.1.7 on 2025-08-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahyogamApp', '0005_alter_volunteer_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
