# Generated by Django 5.1.7 on 2025-08-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahyogamApp', '0006_organization_profile_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('skills_required', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('total_volunteers_needed', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time_slot', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='static/campaign_banners/')),
                ('additional_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
