# Generated by Django 5.1.7 on 2025-08-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahyogamApp', '0007_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='applied',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
