# Generated by Django 5.1.7 on 2025-08-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahyogamApp', '0008_campaign_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='postedBy',
            field=models.CharField(default='KAMALKETULORG', max_length=200),
            preserve_default=False,
        ),
    ]
