# Generated by Django 5.1.7 on 2025-09-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahyogamApp', '0010_campaign_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='organization',
        ),
    ]
