# Generated by Django 5.1.7 on 2025-09-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahyogamApp', '0011_remove_campaign_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sahyogamApp.organization'),
            preserve_default=False,
        ),
    ]
