# Generated by Django 5.1.7 on 2025-09-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahyogamApp', '0012_campaign_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='organization',
            new_name='organizationID',
        ),
    ]
