# Generated by Django 5.1.7 on 2025-09-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahyogamApp', '0014_appliedcampaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedcampaign',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='appliedcampaign',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='appliedcampaign',
            name='campaignPK',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appliedcampaign',
            name='volunteerPK',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
