# Generated by Django 5.1.7 on 2025-09-18 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahyogamApp', '0015_remove_appliedcampaign_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcampaign',
            name='campaignPK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahyogamApp.campaign'),
        ),
        migrations.AlterField(
            model_name='appliedcampaign',
            name='volunteerPK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahyogamApp.volunteer'),
        ),
    ]
