# Generated by Django 5.1.7 on 2025-09-19 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahyogamApp', '0016_alter_appliedcampaign_campaignpk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedcampaign',
            old_name='campaignPK',
            new_name='campaign',
        ),
        migrations.RenameField(
            model_name='appliedcampaign',
            old_name='volunteerPK',
            new_name='volunteer',
        ),
    ]
