# Generated by Django 5.1.7 on 2025-09-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahyogamApp', '0017_rename_campaignpk_appliedcampaign_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedcampaign',
            name='certificate_approved',
            field=models.BooleanField(default=False),
        ),
    ]
