# Generated by Django 5.1.7 on 2025-10-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahyogamApp', '0018_appliedcampaign_certificate_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcampaign',
            name='applied_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
