# Generated by Django 5.1.7 on 2025-10-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahyogamApp', '0019_alter_appliedcampaign_applied_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='time_slot',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
